server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          # Mac OS
          # search-locations: file://${user.home}/IdeaProjects/Spring-MSA/git-local-repo
          # Win OS
          search-locations: file:///${user.home}/Desktop/Spring-MSA/git-local-repo
#          search-locations: file:///C:/Users/Osstem/Desktop/Spring-MSA/git-local-repo
        git:
          uri: https://github.com/Paransaik/Spring-MSA
#          username:
#          password:
          search-paths: /git-local-repo
          default-label: main

