server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Paransaik/Spring-MSA
          search-paths: git-local-repo/**
          default-label: main